### ISSUE TITLE
Change remaining icons according to material design

### ISSUE THREAD

**Issue by vinodrathod9-5** [RTruth/ProjectManager#4]
Right now, the front page looks good but do also change the icons for all the pages inside

**Comment by vinodrathod9-5** [comment]
you can get the icons from https://www.google.com/design/icons/

**Comment by miprathm** [comment]
I follow the guidelines below please check it,
If anything wrong then specify size of icons I will update as per size

https://www.google.co.in/design/spec/components/tabs.html#tabs-specs

**Comment by vinodrathod9-5** [comment]
What you do is increase the size ie. 48 dp as our tab is icon only their is no text on the tab right.

**Comment by miprathm** [comment]
I've shared an item with you:

app-debug.apk
https://drive.google.com/file/d/0B34gkMAEwQ4QLXRuaFVkZ3hhVVk/view?usp=sharing&invite=CNuepasI

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by vinodrathod9-5** [comment]
@prathm92 thank you yaar

**Comment by miprathm** [comment]
Always welcome

**Comment by vinodrathod9-5** [comment]
please wait until i get response from the client & then close this issue. Okay

**Comment by vinodrathod9-5** [comment]
Hello have you checked drawable folder again?

I think it's still same as original.
I want you change the icon design of "drawable" folder.
Not such kind of "drawable-hdpi-v4" folder.

Check the "drawable" folder's icons?
