### ISSUE TITLE
getting a error of this sort on uploading

### ISSUE THREAD

**Issue by raaz4ever** [RTruth/ProjectManager#7]
<br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><font face='Arial' size='1' color='#000000'><b>PHP Error Message</b></font></td></tr></table><br />
    <b>Warning</b>:  fopen(profilePic/) [<a href='function.fopen'>function.fopen</a>]: failed to open stream: Is a directory in <b>/home/a1729105/public_html/uploadProfilePic.php</b> on line <b>15</b><br />
    <br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><div align='center'><a href='http://www.000webhost.com/'><font face='Arial' size='1' color='#000000'>Free Web Hosting</font></a></div></td></tr></table><br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><font face='Arial' size='1' color='#000000'><b>PHP Error Message</b></font></td></tr></table><br />
    <b>Warning</b>:  fclose(): supplied argument is not a valid stream resource in <b>/home/a1729105/public_html/uploadProfilePic.php</b> on line <b>18</b><br />
    <br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><div align='center'><a href='http://www.000webhost.com/'><font face='Arial' size='1' color='#000000'>Free Web Hosting</font></a></div></td></tr></table>You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'http://chemistplus.in/profilePic/ WHERE id =' at line 1

**Comment by vinodrathod9-5** [comment]
Now I have changed the path for saving the profile pic. Please make sure you post `image` parameter in the bitmap string and `filename` for the file name and also make sure you also post the `userID` also.

**Comment by raaz4ever** [comment]
try this php code
<?php
    // Get image string posted from Android App
    $base=$_REQUEST['image'];
    // Get file name posted from Android App
    $filename = $_REQUEST['filename'];
    // Decode Image
    $binary=base64_decode($base);
    header('Content-Type: bitmap; charset=utf-8');
    // Images will be saved under 'www/imgupload/uplodedimages' folder
    $file = fopen('uploadedimages/'.$filename, 'wb');
    // Create File
    fwrite($file, $binary);
    fclose($file);
    echo 'Image upload complete, Please check your php file directory';
?>

**Comment by vinodrathod9-5** [comment]
ok changed to as you requested

**Comment by vinodrathod9-5** [comment]
and always embed the code `your code` .Okay

**Comment by vinodrathod9-5** [comment]
Please remember to format code using triple backticks (`) so that it is neatly formatted when the issue is posted.

**Comment by raaz4ever** [comment]
// Get file name posted from Android App
$filename = $_REQUEST['filename'];
//Get userid posted from Android App
$userid=$_REQUEST['user_id'];

**Comment by raaz4ever** [comment]
<br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><font face='Arial' size='1' color='#000000'><b>PHP Error Message</b></font></td></tr></table><br />
    <b>Warning</b>:  json_encode() expects exactly 1 parameter, 2 given in <b>/home/a1729105/public_html/uploadProfilePic.php</b> on line <b>51</b><br />
    <br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><div align='center'><a href='http://www.000webhost.com/'><font face='Arial' size='1' color='#000000'>Free Web Hosting</font></a></div></td></tr></table>

**Comment by vinodrathod9-5** [comment]
Yes changed it as same

**Comment by raaz4ever** [comment]
chk above php error

**Comment by vinodrathod9-5** [comment]
yes checked, now please again test it.

**Comment by raaz4ever** [comment]
<br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><font face='Arial' size='1' color='#000000'><b>PHP Error Message</b></font></td></tr></table><br />
    <b>Warning</b>:  json_encode() expects exactly 1 parameter, 2 given in <b>/home/a1729105/public_html/uploadProfilePic.php</b> on line <b>38</b><br />
    <br><table border='1' cellpadding='2' bgcolor='#FFFFDF' bordercolor='#E8B900' align='center'><tr><td><div align='center'><a href='http://www.000webhost.com/'><font face='Arial' size='1' color='#000000'>Free Web Hosting</font></a></div></td></tr></table>

**Comment by vinodrathod9-5** [comment]
jakhas 👌👌👌👌👌
